export const ENV_VARS_LIST = {
  PORT: "globals.port",
  MONGODB_URI: "globals.mongodb_uri",
  JWT_SECRET: "globals.jwt_secret",
  OG_MAIL: "mail.og_mail",
  OG_MAIL_PASS: "mail.og_mail_pass",
  SUPPORT_MAIL: "mail.support_mail",
  SUPPORT_MAIL_PASS: "mail.support_mail_pass",
  MAIL_SERVICE: "mail.mail_service",
  MAIL_HOST: "mail.mail_host",
  MAIL_PORT: "mail.mail_port",
  MAIL_ENCRYPTION: "mail.mail_encryption",
  TYPE: "config.type",
  PROJECT_ID: "config.project_id",
  PRIVATE_KEY_ID: "config.private_key_id",
  PRIVATE_KEY: "config.private_key",
  CLIENT_EMAIL: "config.client_email",
  CLIENT_ID: "config.client_id",
  AUTH_URI: "config.auth_uri",
  TOKEN_URI: "config.token_uri",
  AUTH_PROVIDER_X509_CERT_URL: "config.auth_provider_x509_cert_url",
  CLIENT__X509_CERT_URL: "config.client_x509_cert_url",
  UNIVERSE_DOMAIN: "config.universe_domain",
  API_KEY: "config.api_key",
  AUTH_DOMAIN: "config.auth_domain",
  STORAGE_BUCKET: "config.storage_bucket",
  MESSAGING_SENDER_ID: "config.messaging_sender_id",
  APP_ID: "config.app_id",
  MEASUREMENT_ID: "config.measurement_id",
};

export const IMAGE_SIZES = {
  sm: { width: 96, height: 96 },
  md: { width: 268, height: 326 },
  lg: { width: 384, height: 384 },
};
