name: Deploy to Firebase

on:
  push:
    branches:
      - master

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Build client and admin apps
        run: |
          npm --prefix ./client install
          npm --prefix ./client run build
          npm --prefix ./admin install
          npm --prefix ./admin run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install functions dependencies
        run: npm --prefix ./functions ci

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KARINAS_64571 }}
          channelId: live
          projectId: karinas-64571
